export default [
  {
    id: 1,
    title: "Nike Air Max",
    price: "150",
    img: "https://m.media-amazon.com/images/I/51s+egIlArS._UL1200_.jpg",
    description: "The Nike Air Max shoes are known for their stylish design and comfortable fit.",
    quantity: 1,
    category: "Shoes",
  },
  {
    id: 2,
    title: "Adidas Ultraboost",
    price: "180",
    img: "https://m.media-amazon.com/images/I/61LbYsbODrL._UL1500_.jpg",
    description: "The Adidas Ultraboost sneakers combine style and performance.",
    quantity: 1,
    category: "Shoes",
  },
  {
    id: 3,
    title: "Puma Suede",
    price: "800",
    img: "https://www.sneakersnstuff.com/images/89546/original.jpg",
    description: "The Puma Suede shoes are a classic choice for sneaker enthusiasts.",
    quantity: 1,
    category: "Shoes",
  },
  {
    id: 4,
    title: "Reebok",
    price: "500",
    img: "https://i.pinimg.com/originals/b7/a7/7f/b7a77fc1e7a9604f63ebde14de37e9a7.jpg",
    description: "Reebok is perfect for hiking and outdoor adventures.",
    quantity: 1,
    category: "Backpacks",
  },
  {
    id: 5,
    title: "Addidas",
    price: "700",
    img: "https://ae01.alicdn.com/kf/UT8tB6hXpdbXXagOFbX0/XSKN-Stylish-15-inch-Shockproof-Laptop-Computer-Backpack-Multipurpose-Shoulder-School-Bag-Case-for-Notebook-Macbook.jpg_640x640.jpg",
    description: "Addidas is a stylish and durable backpack for everyday use.",
    quantity: 1,
    category: "Backpacks",
  },
  {
    id: 6,
    title: "Puma",
    price: "900",
    img: "https://ae01.alicdn.com/kf/HTB1A5s5XcnrK1RkHFrdq6xCoFXa1/Fouvor-Unisex-Design-Backpack-Book-Bags-for-School-Backpack-Casual-Rucksack-Daypack-Oxford-Canvas-Laptop-Fashion.jpg_640x640.jpg",
    description: "Carry your essentials in style with puma.everyday use.",
    quantity: 1,
    category: "Backpacks",
  },
  // Special Offer Product
  {
    id: 7,
    title: "x-box",
    price: "600",
    img: "https://m.media-amazon.com/images/I/61J0aqLw8NL._SX466_.jpg",
    description: "Get this special offer product at an unbeatable price.",
    quantity: 1,
    category: "Special Offers",
  },

];
